MyMarket/Controllers/CarrinhoComprasController.cs
using Microsoft.AspNetCore.Mvc;
using MyMarket.Database;
using MyMarket.Models;
using MyMarket.ViewsModels;

namespace MyMarket.Controllers
{
    public class CarrinhoComprasController : Controller
    {
        private readonly Context _bancocontext;
        
        public CarrinhoComprasController(Context context)
        {

            _bancocontext = context;
          
        }

        public async Task<IActionResult> Index()
        {
            var carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext, _bancocontext);
            var viewModel = new CarrinhoComprasViewModel
            {
                CartItems = carrinho.GetCarrinhoItens(),
                CarinhoTotal = carrinho.GetTotal()
          };
             return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id)
        {
            var addedProduto = _bancocontext.produtos.Single(
                produto => produto.id == id);

            var carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext, _bancocontext);

             _bancocontext.Add(carrinho);
            await _bancocontext.SaveChangesAsync();
            return RedirectToAction("index");
        }

        [HttpPost]
        public ActionResult RemoveCarrinho(int id)
        {
            var carrinho = CarrinhoCompras.GetCarrinho(this.HttpContext, _bancocontext);

            string produtoNome = _bancocontext.carrinhos.Single(
                item => item.recordId == id).produto.nomeProduto;

            int ItemCount = carrinho.RemoverFromCarrinho(id);

            var results = new CarrinhoComprasRemoveViewModel
            {
                Message = System.Web.HttpUtility.HtmlEncode(produtoNome) +
                "Voce deseja remover o carrinho de compras.",
                CarrinhoTotal = carrinho.GetTotal(),
                CarrinhoCount = carrinho.GetCount(),
                ItemCount = ItemCount,
                DeleteId = id
            };
            return Json(results);
        }
    }
   
}

MyMarket/Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace MyMarket.Controllers
{
    public class EnderecoController : Controller
    {
        // GET: EnderecoController
        public ActionResult Index()
        {
            return View();
        }

        // GET: EnderecoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EnderecoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EnderecoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EnderecoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: EnderecoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EnderecoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: EnderecoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MyMarket/Views/Shared/components/Menu/default.cshtml
@model Usuario
<div class="btn btn-light btn-outline-primary">
    <img class="logo" src="../" />
</div>
<ul class="navbar-nav ms-auto" >

<p>
    @using (Html.BeginForm())
    {
        @Html.TextBox("searchstring")
    }

</p>
</ul>
 <ul class="navbar-nav ms-auto">
<li class="nav=item m-1">
    <a class="btn  btn-outline-light" asp-controller="CarrinhoCompras" asp-action="Index">
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z" />
        </svg>
    </a>
</li>


        <li class="nav-item dropdown ">
            <a class="nav-link dropdown-toggle text-white" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Minha Conta
            </a>
            <ul class="dropdown-menu dropdown-menu-dark  fs-5" aria-labelledby="navbarDropdown">
                 <li><a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Edit">Meus dados</a></li>
                 <li><a class="dropdown-item" asp-area="" asp-controller="Endereco" asp-action="Create"> Meus endereços</a></li>
                <li><a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Sair">Sair</a></li>
            </ul>
        </li>
    </ul>